site_name: Laravel Roles
docs_dir: docs
theme_dir: 'docs/mkdocs-material'
extra:
    palette:
        primary: 'red'
pages:
    - Home: 'index.md'
    - Getting Started:
        - 'Installation': 'getting-started/installation.md'
        - 'Configuration': 'getting-started/configuration.md'
    - Concepts:
        - 'Roles': 'core-concepts/roles.md'
        - 'Permits': 'core-concepts/permits.md'
    - Views:
        - 'Blade Syntax': 'views/blade-syntax.md'