site_name: Laravel Roles
docs_dir: doc
pages:
    - Home: 'index.md'
    - Getting Started:
        - 'Installation': 'getting-started/installation.md'
        - 'Configuration': 'getting-started/configuration.md'
    - Concepts:
        - 'Roles': 'concepts/roles.md'
        - 'Permits': 'concepts/permits.md'
    - Views: