site_name: Laravel Roles
docs_dir: docs
theme_dir: 'docs/mkdocs-material'
extra:
    palette:
        primary: 'red'
pages:
    - Home: 'index.md'
    - Getting Started:
        - 'Installation': 'installation.md'
        - 'Configuration': 'configuration.md'
    - Concepts:
        - 'Roles': 'roles.md'
        - 'Permits': 'permits.md'
    - Views:
        - 'Blade Syntax': 'blade-syntax.md'